---
# We do this to capture which group was created during install
# https://github.com/mrlesmithjr/ansible-kvm/pull/2
- name: config_kvm | Capturing Libvirt Group
  shell: "getent group libvirt | cut -d: -f1"
  register: "_libvirt_group_found"
  changed_when: false

# We do this to capture which group was created during install
# https://github.com/mrlesmithjr/ansible-kvm/pull/2
- name: config_kvm | Capturing Libvirt Group
  shell: "getent group libvirtd | cut -d: -f1"
  register: "_libvirtd_group_found"
  changed_when: false

- name: set_facts | Setting unix_sock_group
  set_fact:
    kvm_unix_sock_group: 'libvirt'
  when: _libvirt_group_found['stdout'] == 'libvirt'

- name: set_facts | Setting unix_sock_group
  set_fact:
    kvm_unix_sock_group: 'libvirtd'
  when: _libvirtd_group_found['stdout'] == 'libvirtd'

- name: config_kvm | configuring kvm
  template:
    src: "etc/libvirt/libvirtd.conf.j2"
    dest: "/etc/libvirt/libvirtd.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  become: true
  notify:
    - "restart {{ kvm_service_name }}"
  when: ansible_os_family == "Debian"

- name: config_kvm | configuring kvm
  replace:
    dest: "/etc/default/libvirt-bin"
    regexp: "^libvirtd_opts=\"-d\""
    replace: "libvirtd_opts=\"-d -l\""
  become: true
  notify:
    - "restart {{ kvm_service_name }}"
  when: >
        kvm_enable_tcp and
        ansible_os_family == "Debian"
