---
- name: config_kvm | configuring kvm
  template:
    src: "etc/libvirt/libvirtd.conf.j2"
    dest: "/etc/libvirt/libvirtd.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  become: true
  notify:
    - "restart {{ kvm_service_name }}"
  when: ansible_os_family == "Debian"

- name: config_kvm | configuring kvm
  replace:
    dest: "/etc/default/libvirt-bin"
    regexp: "^libvirtd_opts=\"-d\""
    replace: "libvirtd_opts=\"-d -l\""
  become: true
  notify:
    - "restart {{ kvm_service_name }}"
  when: >
        kvm_enable_tcp and
        ansible_os_family == "Debian"
