---
- name: debian | Installing KVM
  apt:
    name: "{{ item }}"
    state: present
  become: true
  register: result
  until: result is successful
  with_items: "{{ kvm_debian_packages }}"

- name: debian | Installing Additional Ubuntu Packages
  apt:
    name: ["ubuntu-vm-builder"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Ubuntu"
