---
# tasks file for ansible-kvm
- include: hw_virtualization_check.yml

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config_kvm.yml
  tags:
    - config_kvm
  when: >
        config_kvm is defined and
        config_kvm

- include: users.yml
  tags:
    - config_users
  when: >
        (kvm_config_users is defined and
          kvm_config_users) and
          kvm_users is defined

- include: config_ssh.yml
  tags:
    - config_ssh
  when: >
        kvm_allow_root_ssh is defined and
        kvm_allow_root_ssh

- include: config_virtual_networks.yml
  tags:
    - config_virtual_networks
  when: >
        (kvm_config_virtual_networks is defined and
          kvm_config_virtual_networks) and
          kvm_virtual_networks is defined

- include: system_tweaks.yml
