---
- name: nfs | installing pre-reqs
  apt: name={{ item }} state=present
  with_items:
    - nfs-common

- name: nfs | mounting NFS volumes
  mount: name={{ item.mountpoint }} src={{ item.server }}:{{ item.export }} fstype=nfs opts={{ item.mount_options }} state=mounted
  with_items: nfs_mounts