---
- name: set_facts | Setting Debian Facts
  set_fact:
    kvm_service_name: 'libvirtd'
  when: ansible_distribution == "Debian"

- name: set_facts | Setting Ubuntu Facts
  set_fact:
    kvm_service_name: 'libvirt-bin'
  when: ansible_distribution == "Ubuntu"
