---
# handlers file for ansible-kvm
- name: restart libvirt-bin
  service:
    name: "libvirt-bin"
    state: "restarted"
  become: true

- name: restart libvirtd
  service:
    name: "libvirtd"
    state: "restarted"
  become: true

- name: restart ssh
  service:
    name: "ssh"
    state: "restarted"
  become: true
